DROP TABLE IF EXISTS PLAYER CASCADE;
DROP TABLE IF EXISTS TEAM CASCADE;
DROP TABLE IF EXISTS COLOR CASCADE;
DROP TABLE IF EXISTS STATE CASCADE;

CREATE TABLE STATE(
STATE_ID SERIAL PRIMARY KEY,
NAME VARCHAR(32) NOT NULL
);

CREATE TABLE COLOR(
COLOR_ID SERIAL PRIMARY KEY,
NAME VARCHAR(32)
);

CREATE TABLE TEAM(
TEAM_ID SERIAL PRIMARY KEY,
NAME VARCHAR(32) NOT NULL,
STATE_ID INT NOT NULL,
COLOR_ID INT NOT NULL,
WINS INT NOT NULL,
LOSSES INT NOT NULL,
CONSTRAINT STATE_FK FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID) ON DELETE SET NULL ON UPDATE CASCADE,
CONSTRAINT COLOR_FK FOREIGN KEY (COLOR_ID) REFERENCES COLOR(COLOR_ID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE PLAYER(
PLAYER_ID SERIAL PRIMARY KEY,
TEAM_ID INT NOT NULL,
UNIFORM_NUM INT NOT NULL,
FIRST_NAME VARCHAR(32) NOT NULL,
LAST_NAME VARCHAR(32) NOT NULL,
MPG INT NOT NULL,
PPG INT NOT NULL,
RPG INT NOT NULL,
APG INT NOT NULL,
SPG FLOAT8 NOT NULL,
BPG FLOAT8 NOT NULL,
CONSTRAINT TEAM_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE SET NULL ON UPDATE CASCADE
);




